services:
  - type: web
    name: carauction-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:80
      - key: DATABASE_URL
        fromDatabase:
          name: carauction-db
          property: connectionString
    healthCheckPath: /api/cars
  
  - type: pserv
    name: carauction-db
